version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: ⬆ [dependabot]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: ⬆ [dependabot]
    groups:
      angular:
        patterns:
          - "@angular*"
